version: '3.8' # Updated Docker Compose version

services:
    redis:
        image: redis:alpine
        container_name: ecommerce-redis
        ports:
            - '6379:6379'
        networks:
            - ecommerce-networks
        volumes:
            - redis_data:/data

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
        container_name: ecommerce-elasticsearch
        environment:
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
        ports:
            - '9200:9200'
            - '9300:9300'
        networks:
            - ecommerce-networks
        volumes:
            - es_data:/usr/share/elasticsearch/data
        ulimits:
            memlock:
                soft: -1
                hard: -1

    kibana:
        image: docker.elastic.co/kibana/kibana:8.15.1
        container_name: ecommerce-kibana
        environment:
            - ELASTICSEARCH_HOSTS=http://ecommerce-elasticsearch:9200
        ports:
            - '5601:5601'
        networks:
            - ecommerce-networks

networks:
    ecommerce-networks:
        driver: bridge

volumes:
    redis_data:
    es_data:
